from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]


def test_expected_project_structure_exists() -> None:
    expected_paths = [
        "pyproject.toml",
        "README.md",
        ".env.example",
        ".gitignore",
        "Documentos",
        "data/processed",
        "data/eval",
        "data/eval/evaluation_questions.jsonl",
        "data/eval/reports",
        "data/chunks",
        "storage/chroma",
        "logs",
        "src/rag_chatbot/__init__.py",
        "src/rag_chatbot/config.py",
        "src/rag_chatbot/diagnostics.py",
        "src/rag_chatbot/logging_config.py",
        "src/rag_chatbot/local_pipeline.py",
        "src/rag_chatbot/schemas.py",
        "src/rag_chatbot/cli.py",
        "src/rag_chatbot/api/main.py",
        "src/rag_chatbot/api/routes.py",
        "src/rag_chatbot/api/models.py",
        "src/rag_chatbot/api/dependencies.py",
        "src/rag_chatbot/ui/__init__.py",
        "src/rag_chatbot/ui/api_client.py",
        "src/rag_chatbot/ui/streamlit_app.py",
        "src/rag_chatbot/ingestion/discovery.py",
        "src/rag_chatbot/ingestion/hashing.py",
        "src/rag_chatbot/ingestion/loaders.py",
        "src/rag_chatbot/ingestion/manifest.py",
        "src/rag_chatbot/ingestion/pipeline.py",
        "src/rag_chatbot/chunking/cleaning.py",
        "src/rag_chatbot/chunking/splitter.py",
        "src/rag_chatbot/chunking/pipeline.py",
        "src/rag_chatbot/embeddings/base.py",
        "src/rag_chatbot/embeddings/sentence_transformers_provider.py",
        "src/rag_chatbot/vectorstores/base.py",
        "src/rag_chatbot/vectorstores/chroma_store.py",
        "src/rag_chatbot/indexing/__init__.py",
        "src/rag_chatbot/indexing/pipeline.py",
        "src/rag_chatbot/retrieval/formatting.py",
        "src/rag_chatbot/retrieval/retriever.py",
        "src/rag_chatbot/rag/pipeline.py",
        "src/rag_chatbot/rag/answer_builder.py",
        "src/rag_chatbot/rag/guardrails.py",
        "src/rag_chatbot/rag/domain_guardrails.py",
        "src/rag_chatbot/rag/citations.py",
        "src/rag_chatbot/evaluation/dataset.py",
        "src/rag_chatbot/evaluation/calibration.py",
        "src/rag_chatbot/evaluation/evaluator.py",
        "src/rag_chatbot/evaluation/grid.py",
        "src/rag_chatbot/evaluation/metrics.py",
        "src/rag_chatbot/evaluation/reporting.py",
        "tests/__init__.py",
        "tests/test_project_structure.py",
        "tests/test_config.py",
        "tests/test_cli.py",
        "tests/test_discovery.py",
        "tests/test_hashing.py",
        "tests/test_loaders.py",
        "tests/test_manifest.py",
        "tests/test_ingestion_pipeline.py",
        "tests/test_cleaning.py",
        "tests/test_splitter.py",
        "tests/test_chunking_pipeline.py",
        "tests/test_embeddings.py",
        "tests/test_chroma_store.py",
        "tests/test_indexing_pipeline.py",
        "tests/test_retrieval_formatting.py",
        "tests/test_retriever.py",
        "tests/test_rag_citations.py",
        "tests/test_rag_guardrails.py",
        "tests/test_rag_answer_builder.py",
        "tests/test_rag_pipeline.py",
        "tests/test_evaluation_dataset.py",
        "tests/test_evaluation_metrics.py",
        "tests/test_evaluation_reporting.py",
        "tests/test_evaluation_grid.py",
        "tests/test_evaluator.py",
        "tests/test_api_models.py",
        "tests/test_api_routes.py",
        "tests/test_diagnostics.py",
        "tests/test_local_pipeline.py",
        "tests/test_ui_api_client.py",
    ]

    missing = [path for path in expected_paths if not (PROJECT_ROOT / path).exists()]

    assert missing == []
